name: Detect Actions Installed

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Clean Up Environment
      run: |
        sudo apt list --installed > installed.txt

    - name: Upload installed.txt
      uses: actions/upload-artifact@v4
      with:
        name: installed
        path: installed.txt